version: '3'
services:
  lite_server:
    image: "node:12"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 8080:3000
    command: bash -c "pwd && cd app && npm i -g lite-server && lite-server"